### ISSUE TITLE
Integrate RevX with other robot code

### ISSUE THREAD

**Issue by msbense** [team5181/2016Robot#31]
We can probably use RevX to correct for mistakes in auton, control sensitive actuators, etc

**Comment by frjalex** [comment]
#18 it shall also coorporate with vision now

**Comment by Connor-Devitt** [comment]
Everything that you try to correct in Austin has the possibility of creating a new problem. If you use revX to add an action in order to correct an error, the rest of the recording will be late and eventually cut off. If you try to incorporate an adjustment into the recording itself, you loose the context of the action (you may turn and hit something but still be "right" according to the auton). It will be difficult to correct the auton error

**Comment by Connor-Devitt** [comment]
Auton not Austin

**Comment by frjalex** [comment]
I told you, I told you!

**Comment by Connor-Devitt** [comment]
Yes. But we must test auton. I forget how inaccurate it is if it is inaccurate at all. We may find that we do not need to correct it- otherwise the solution is completely dependent on the problem

**Comment by frjalex** [comment]
There are only three probabilities - too quick, not enough and too slow.
All these I believe can be adjusted using a function modeling the timeStep
variable instead of autoturning.

**Comment by Connor-Devitt** [comment]
If it is a timing issue we can simply change autonomous like you said. If it is not a timing issue however..... We should test today-make sure that the error is actually why we think it is.

**Comment by frjalex** [comment]
There can't be an assumed "issue" "as if", in my opinion the only possible
turning issue is the inner fluctuation of rotors or external hampers that
leads to not enough turning/overturning. This probably can be solved by
speeding up replaying a part of the recording.

**Comment by msbense** [comment]
Alex, you're wrong. There are three POSSIBILITIES. Each of which has a PROBABILITY. 
Thats all I have to say about that

**Comment by frjalex** [comment]
@msbense, sorry, I apologize for the wording.

**Comment by Connor-Devitt** [comment]
Check out auton. I think I found the problem. The time in thread.sleep % the count increment is not 0. --so the actual delay in auton is less than the count increment. If we change how we increment count, there should be no problem. If it works we don't have to worry about a live time difference calculator or worry about any other timing problems

**Comment by frjalex** [comment]
But wouldn't an increment of 0 equal to having NO TIMESTEP at all?

**Comment by frjalex** [comment]
Plus I think we're really talking about external interrupts here but not measurable/considerable delay

**Comment by Connor-Devitt** [comment]
I mean the remainder when the thread sleep is divided by the count increment. And it might actually play back slower

**Comment by msbense** [comment]
For reference:
```
Autonomous.java:
32				while(count <= timeStep) {	 
33 					robot.teleopMaster(true); 
34 					Gamepad.setSyntheticState(command); 
35 					Thread.sleep(1); 
36 					count += (1 + 0.388);					 
37 					if(!inAuton) { 
38 						break; 
39 					} 
40 				} 
```
So this is saying that the amount of time passed is the length of the call to Thread.Sleep() (1)  and the time it takes to run an iteration of this loop (0.388). 
My questions are:

1. Why does the time in thread.sleep % the count increment have to be 0?
2. Why doesn't the thread.sleep cause the robot to stop moving altogether for that period of time? Is it because the thread is sleeping for only a short time?

**Comment by frjalex** [comment]
Mark, 1) It doesnt have to be 0. Actually, thread.sleep shall be removed if
set to 0 since it won't be functioning. 2) Actually it does. Based on
previous experiments Connor and I have concluded that Thread.sleep will
SIGNIFICANTLY hamper the movement between timeSteps of the robot if set to
a reasonably large amount. Since it is using miliseconds as an input
interval 1ms will not cause significant delays nor will the delays be
visible.

**Comment by Connor-Devitt** [comment]
Alex I'm not saying the we should Set thread sleep to zero. Actually the opposite. Currently if you look at the code segment timeDelay is 1ms so the whole loop executes: the code takes 0.388 ms to execute and the thread sleeps for 1 ms. Then count is increments by 1.388 and the while is reevaluated. The Boolean test fails since 1.388 >= 1 and the next command is executed. Therefore the auton executes .388 ms slower than the recording so by the end of the recording, auton will be off since the recording was recorded where 1 command is recorded each 1 ms

**Comment by frjalex** [comment]
I am confused - so what do you want to change?

**Comment by frjalex** [comment]
I think by now we're all clear that RevX is to be used with Auton, and as the codes are already written and pushed, this shall be closed.
